# IHCP CGM Solver 設定ファイル例
#
# このファイルは逆熱伝導問題（IHCP）を共役勾配法（CGM）で解く際の
# 設定パラメータを定義します

# ============================================================================
# 問題設定（Problem Configuration）
# ============================================================================
[problem]
# 空間格子点数
ni = 10          # x方向格子点数
nj = 10          # y方向格子点数
nk = 20          # z方向格子点数（深さ方向）

# 格子幅
dx = 0.12e-3     # x方向格子幅 [m] (0.12mm)
dy = 0.12e-3     # y方向格子幅 [m] (0.12mm)

# z方向格子幅の指定方法（いずれか1つ）
# オプション1: ファイルから読み込み
# dz_file = "config/dz_grid.txt"

# オプション2: 配列で直接指定（20要素 = nk）
# 表面に細かい格子、底面に粗い格子（非均等格子）
dz = [
  0.5e-4, 0.5e-4, 0.5e-4, 0.5e-4, 0.5e-4,  # 表面側5層: 0.05mm
  1.0e-4, 1.0e-4, 1.0e-4, 1.0e-4, 1.0e-4,  # 中間5層: 0.10mm
  1.5e-4, 1.5e-4, 1.5e-4, 1.5e-4, 1.5e-4,  # 中間5層: 0.15mm
  2.0e-4, 2.0e-4, 2.0e-4, 2.0e-4, 2.0e-4   # 底面側5層: 0.20mm
]

# 時間設定
nt = 1000        # 時間ステップ数
dt = 1.0e-3      # 時間刻み幅 [s] (1ms)

# ============================================================================
# 材料特性（Material Properties）
# ============================================================================
[material]
# SUS304ステンレス鋼の物性値

# 密度 [kg/m³]
rho = 7900.0

# 比熱の多項式係数 [J/(kg·K)]
# cp(T) = a0*T³ + a1*T² + a2*T + a3
cp_coeffs = [4.184e-7, -0.0009168, 1.34436, 233.604]

# 熱伝導率の多項式係数 [W/(m·K)]
# k(T) = b0*T³ + b1*T² + b2*T + b3
k_coeffs = [9.2486e-6, -0.01356, 8.21814, 7821.93]

# ============================================================================
# 共役勾配法（CGM）設定
# ============================================================================
[cgm]
# CGM最大反復回数
max_iter = 50

# 測定誤差の標準偏差 [K]
sigma = 0.1

# 許容誤差（DHCP）
rtol_dhcp = 1.0e-6

# 許容誤差（Adjoint）
rtol_adjoint = 1.0e-8

# CG法の最大反復回数
maxiter_cg = 20000

# ============================================================================
# スライディングウィンドウ設定
# ============================================================================
[sliding_window]
# ウィンドウサイズ（時間ステップ数）
window_size = 100

# オーバーラップ（時間ステップ数）
# 0の場合、ウィンドウ間でデータを共有しない
overlap = 20

# 初期熱流束 [W/m²]
q_init_value = 0.0

# ============================================================================
# 入力データ設定
# ============================================================================
[input]
# 初期温度場
# オプション1: ファイルから読み込み（.npy, .txt, .mat）
T_init_file = "data/T_init.npy"

# オプション2: 直接指定（形状: ni×nj×nk）
# T_init = [...]

# 観測温度（底面温度）
# オプション1: ファイルから読み込み（.npy, .txt, .mat）
Y_obs_file = "data/Y_obs.npy"

# オプション2: 直接指定（形状: ni×nj×nt）
# Y_obs = [...]

# MATファイルディレクトリ（オプション）
# IRカメラデータを直接使用する場合
# mat_files_dir = "data/MAT_files/"

# ============================================================================
# 出力設定
# ============================================================================
[output]
# 出力形式（jld2/npz/both）
save_format = "jld2"

# ウィンドウ情報を保存
save_windows_info = true

# 収束履歴を保存
save_convergence_history = true

# ============================================================================
# 可視化設定
# ============================================================================
[visualization]
# 可視化を有効化
enabled = true

# 熱流束の時間変化プロット
plot_heat_flux = true

# ヒートマップ
plot_heatmap = true

# CGM収束履歴
plot_convergence = true

# 出力ディレクトリ
output_dir = "plots/"

# 画像形式（png/pdf/svg）
format = "png"

# ヒートマップの時刻指定（秒単位）
# 空配列の場合、中間時刻のみプロット
heatmap_times = [0.1, 0.25, 0.5]
