# IHCP CGM Solver テスト用設定ファイル
#
# 小規模問題で動作確認を行うための設定

# ============================================================================
# 問題設定（Problem Configuration）- 小規模問題
# ============================================================================
[problem]
# 空間格子点数（小規模）
ni = 3           # x方向格子点数
nj = 3           # y方向格子点数
nk = 5           # z方向格子点数（深さ方向）

# 格子幅
dx = 0.12e-3     # x方向格子幅 [m] (0.12mm)
dy = 0.12e-3     # y方向格子幅 [m] (0.12mm)

# z方向格子幅（5要素 = nk、各層の厚さ）
dz = [1.0e-4, 1.0e-4, 1.0e-4, 1.0e-4, 1.0e-4]

# 時間設定（短時間）
nt = 50          # 時間ステップ数
dt = 1.0e-3      # 時間刻み幅 [s] (1ms)

# ============================================================================
# 材料特性（Material Properties）
# ============================================================================
[material]
# SUS304ステンレス鋼の物性値

# 密度 [kg/m³]
rho = 7900.0

# 比熱の多項式係数 [J/(kg·K)]
cp_coeffs = [4.184e-7, -0.0009168, 1.34436, 233.604]

# 熱伝導率の多項式係数 [W/(m·K)]
k_coeffs = [9.2486e-6, -0.01356, 8.21814, 7821.93]

# ============================================================================
# 共役勾配法（CGM）設定
# ============================================================================
[cgm]
# CGM最大反復回数（テスト用に少なめ）
max_iter = 10

# 測定誤差の標準偏差 [K]
sigma = 0.1

# 許容誤差（DHCP）
rtol_dhcp = 1.0e-6

# 許容誤差（Adjoint）
rtol_adjoint = 1.0e-8

# CG法の最大反復回数
maxiter_cg = 1000

# ============================================================================
# スライディングウィンドウ設定
# ============================================================================
[sliding_window]
# ウィンドウサイズ（時間ステップ数）
window_size = 25

# オーバーラップ（時間ステップ数）
overlap = 5

# 初期熱流束 [W/m²]
q_init_value = 0.0

# ============================================================================
# 入力データ設定（テスト用）
# ============================================================================
[input]
# テスト用データは実行時に生成される
# 以下はプレースホルダー

# 初期温度場（一様温度）
# T_init = 300.0 * ones(ni, nj, nk)

# 観測温度（線形加熱を模擬）
# Y_obs = 300.0 .+ (1:nt)' .* 0.1

# テスト用ファイルパス
T_init_file = "data/test_T_init.npy"
Y_obs_file = "data/test_Y_obs.npy"

# ============================================================================
# 出力設定
# ============================================================================
[output]
# 出力形式
save_format = "jld2"

# ウィンドウ情報を保存
save_windows_info = true

# 収束履歴を保存
save_convergence_history = true
